version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "monthly" }
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "monthly" }
  - package-ecosystem: "npm"
    directory: "cicd-authorisation"
    schedule: { interval: "monthly" }
