version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "daily" }
    assignees: [ "rdok" ]
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "daily" }
    assignees: [ "rdok" ]
  - package-ecosystem: "npm"
    directory: "cicd-authorisation"
    schedule: { interval: "daily" }
    assignees: [ "rdok" ]
