AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  ExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/handler-example.handle
      Runtime: nodejs14.x
      Environment:
        Variables:
          ENV_EXAMPLE: "example_env_value"
