AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  IsProduction:
    Type: String
    Default: "false"
Conditions:
  CreateProdResources: !Equals [!Ref IsProduction, "true"]
Resources:
  ExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/handler-example.handle
      Runtime: nodejs14.x
      Environment:
        Variables:
          ENV_EXAMPLE: "example_env_value"
  MonitorExampleFunction:
    Condition: CreateProdResources
    Type: AWS::CloudWatch::Alarm
    Properties:
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions: [{ Name: FunctionName, Value: !Ref ExampleFunction }]
      EvaluationPeriods: 1
      Period: 60 # 1 minute
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
      AlarmActions: [!Ref MonitorActions]
      OKActions: [!Ref MonitorActions]
  MonitorActions:
    Condition: CreateProdResources
    Type: AWS::SNS::Topic

Outputs:
  MonitorActionsArn:
    Condition: CreateProdResources
    Value: !Ref MonitorActions
    Export: { Name: !Sub "${AWS::StackName}-MonitorActions" }
    Description: "Import this to AWS-Chatbot Slack, to subscribe emails, etc."
