version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "rdok-dev-aws-sam-ts"
s3_bucket = "rdok-cicd-aws-sam-ts"
s3_prefix = "dev"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
