version = 0.1
[prod]
[prod.deploy]
[prod.deploy.parameters]
parameter_overrides=[
    "NodeENV=production",
    "AwsChatBotStackName=rdok-prod-aws-chatbot"
]

[test]
[test.deploy]
[test.deploy.parameters]
parameter_overrides=[
    "NodeENV=test",
    "AwsChatBotStackName=rdok-test-aws-chatbot"
]

[dev]
[dev.deploy]
[dev.deploy.parameters]
parameter_overrides=[
    "NodeENV=dev",
    "AwsChatBotStackName=rdok-test-aws-chatbot"
]
