name: Check
on:
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Setup Node with cache
        uses: actions/setup-node@v3
        with: { node-version: "14", cache: "npm" }
      - name: Install NPM packages
        run: npm ci
      - name: Check prettier
        run: |
          npm run prettier
          CODE=$?
          if [ "$CODE" != "0"  ]; then exit 1; fi

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Setup Node with cache
        uses: actions/setup-node@v3
        with: { node-version: "14", cache: "npm" }
      - name: Install NPM packages
        run: npm ci
      - name: Check eslint
        run: npm run lint

  ts-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Setup Node with cache
        uses: actions/setup-node@v3
        with: { node-version: "14", cache: "npm" }
      - name: Install NPM packages
        run: npm ci
      - name: Compile TypeScript to JavaScript
        run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Setup Node with cache
        uses: actions/setup-node@v3
        with: { node-version: "14", cache: "npm" }
      - name: Install NPM packages
        run: npm ci
      - name: Check tests
        run: npm run test

  cicd-authorisation:
    defaults:
      run:
        working-directory: cicd-authorisation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Setup Node with cache
        uses: actions/setup-node@v3
        with: { cache: "npm" }
      - name: Install NPM packages
        run: npm ci
      - name: Check tests
        run: npm run test
